### ISSUE TITLE
Investigate whether `object.assign` could be replaced with `xtend`

### ISSUE THREAD

**Issue by wooorm** [syntax-tree/unist-builder#1]
...or similar.

I was just checking some sizes of libs I’m making and found that `object.assign` adds about half of the size: `object.assign` is 7kb, minified; 2.58kb, gzipped.

I known, I know, it’s all not a lot, and I’m nitpicking 😉

**Comment by eush77** [comment]
Sure!

How about [object-assign](https://github.com/sindresorhus/object-assign)? It is small **and** has an ES spec behind.

**Comment by wooorm** [comment]
That works for me too! 👍

**Comment by eush77** [comment]
Published in 1.0.2. Thanks!

**Comment by wooorm** [comment]
❤️
