### ISSUE TITLE
Remove the String cast for the node's value

### ISSUE THREAD

**Issue by kamikazePT** [syntax-tree/unist-builder#12]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

I have some use cases in which I would need the value to be an actual value, not cast to string, to work around this I ended up making my own unist-builder without the String() call.

I don't even understand why we want to force string to it, if it's a value, we can even map it or filter it using the unist-filter and unist-map utilities without having to parse/stringify the value.

### Solution

builder shouldn't hard cast to string the value provided, since it limits how we can use the value itself while mixing with other syntax-tree utilities.

### Alternatives

- JSON.parse when needed, which isn't much of a good alternative

**Comment by wooorm** [comment]
> I have some use cases in which I would need the value to be an actual value,

Why?

> why we want to force string

Because these projects are about ASTs. Which represent programming code. So, objects that represent strings. Literals are the smallest possible slice of a document. Hence a string.

> JSON.parse

Why do you want to put JSON in there?
