### ISSUE TITLE
Rename to `astscript`

### ISSUE THREAD

**Issue by wooorm** [syntax-tree/unist-builder#5]
### Subject of the feature

Idea I’m having: this project’s name is very different from hastscript/mdastscript. How about using `astscript`? (it’s free on npm!)

### Problem

Similar projects have different naming schemes.

---

What do you think?

**Comment by wooorm** [comment]
(note that `stscript` would be more accurate, but meh, that’s hard to pronounce)

**Comment by ChristianMurphy** [comment]
:man_shrugging: builder makes sense to me.

I get where you're going with going for consistency, I wonder of `ast` is the right prefix?
None of the syntax-tree repos currently have that prefix.
Would `unistscript` make sense?

**Comment by wooorm** [comment]
I guess it’s fine keeping its original name. unistscript is somewhat nice too though!
