### ISSUE TITLE
Import issue in the package unist-builder in ES6 codebase

### ISSUE THREAD

**Issue by khushal87** [syntax-tree/unist-builder#7]
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 

Affected packages and versions: `unist-builder` 3.0.0

### Steps to reproduce
1. Imported the package into the project using ES6 and typescript.
2. Imported the `u` from the package.
3. Received the importing error.

### Expected behavior

Should run without any issue, but throws import issues.

### Actual behavior

Throwing errors after import.

### Errror
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/khushal87/Projects/RNE-AutoGen/node_modules/unist-builder/index.js
require() of ES modules is not supported.
require() of /home/khushal87/Projects/RNE-AutoGen/node_modules/unist-builder/index.js from /home/khushal87/Projects/RNE-AutoGen/json-to-markdown/mdast/templates.ts is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/khushal87/Projects/RNE-AutoGen/node_modules/unist-builder/package.json.
```

### Fix

1. Remove `type: "module"` from package.json.
2. Export `u` as module.exports = {u};

### Note
The above fix works after doing the following changes in the package code under node_modules. So it will be great if this package adapts the new code so that the issue could be resolved.

**Comment by ChristianMurphy** [comment]
The use of ESM is intended https://github.com/unifiedjs/unified/issues/121
There is also some discussion of how to migrate to ESM there, there are also more resources at https://blog.sindresorhus.com/get-ready-for-esm-aa53530b3f77 and https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#how-can-i-move-my-commonjs-project-to-esm

**Comment by khushal87** [comment]
@ChristianMurphy When is the next version coming up as in unifiedjs/unified#121?

**Comment by ChristianMurphy** [comment]
It's in progress, there are 300+ packages in unified.
unist-builder has it today, is there a specific package you're interested in?

**Comment by khushal87** [comment]
@ChristianMurphy unist-builder, is the one for which I need the fix. Thanks for the reply :raised_hands:
